// Frame loop + integration. OWNER: integrator. Subsystem agents do not edit this file;
// request changes in docs/notes/<area>.md instead.

import * as THREE from 'three';
import type { AppContext, ViewInfo } from '../core/context';
import { EventBus } from '../core/events';
import { DEFAULT_SETTINGS, settingsFromUrl, type Settings } from '../core/settings';
import type { SimSnapshot } from '../core/types';
import { Simulation, type ManualInput, type MissionSummary } from '../sim/Simulation';
import { Environment } from '../render/env/Environment';
import { VehicleVisuals } from '../render/vehicles/VehicleVisuals';
import { VFX } from '../render/vfx/VFX';
import { PostPipeline } from '../render/post/PostPipeline';
import { ViewportManager } from '../cameras/ViewportManager';
import { AudioEngine } from '../audio/AudioEngine';
import { HUD } from '../ui/HUD';
import { QualityManager } from './Quality';

export interface AppActions {
  liftoffNow(): void;
  toggleHold(): void;
  stageSeparation(): void;
  fairingSeparation(): void;
  setWarp(w: number): void;
  togglePause(): void;
  setSetting<K extends keyof Settings>(key: K, value: Settings[K]): void;
  setManualInput(i: ManualInput): void;
  startReplay(): void;
  stopReplay(): void;
  togglePhotoMode(): void;
  unlockAudio(): void;
  restart(): void;
  getSummary(): MissionSummary;
  /** forwarded to ViewportManager.command (e.g. 'cycle', 'restore', 'mode:long_lens') */
  cameraCommand(cmd: string): void;
  /** render one frame and return it as PNG (photo mode) */
  capturePhoto(): Promise<Blob | null>;
}

/** Plays back sim history (slow-mo touchdown replay). */
class ReplayController {
  active = false;
  t = 0;
  end = 0;
  speed = 0.25;
  start(from: number, to: number, speed = 0.25) {
    this.active = true; this.t = from; this.end = to; this.speed = speed;
  }
}

export class App {
  readonly ctx: AppContext;
  readonly sim: Simulation;
  readonly env: Environment;
  readonly vehicles: VehicleVisuals;
  readonly vfx: VFX;
  readonly views: ViewportManager;
  readonly audio: AudioEngine;
  readonly hud: HUD;
  readonly actions: AppActions;
  readonly params = new URLSearchParams(location.search);
  private posts = new Map<string, PostPipeline>();
  private quality: QualityManager;
  private replayCtl = new ReplayController();
  private last = performance.now();
  private lastSnap: SimSnapshot | null = null;
  frameCount = 0;

  constructor(private root: HTMLElement) {
    const canvas = document.createElement('canvas');
    canvas.id = 'gl';
    root.appendChild(canvas);
    const renderer = new THREE.WebGLRenderer({
      canvas,
      antialias: false,
      logarithmicDepthBuffer: true,
      powerPreference: 'high-performance',
      stencil: false,
      preserveDrawingBuffer: this.params.has('shot'), // screenshots / photo mode capture
    });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.toneMapping = THREE.NoToneMapping;
    renderer.autoClear = false;
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;

    const settings = settingsFromUrl(DEFAULT_SETTINGS, this.params);
    const scene = new THREE.Scene();
    const worldRoot = new THREE.Group();
    worldRoot.name = 'worldRoot';
    scene.add(worldRoot);

    this.ctx = {
      renderer, scene, worldRoot,
      renderOrigin: new THREE.Vector3(),
      settings,
      quality: { level: 2, renderScale: 0.9, frameMs: 16 },
      events: new EventBus(),
      lighting: {
        sunDir: new THREE.Vector3(0, 1, 0), sunColor: new THREE.Color(1, 1, 1), sunVisibility: 1,
        skyColor: new THREE.Color(0.4, 0.6, 1), groundColor: new THREE.Color(0.1, 0.12, 0.15),
        envMap: null, exposureBias: 0, moonDir: new THREE.Vector3(0, 1, 0), moonColor: new THREE.Color(0, 0, 0),
      },
      hazeSources: [], plumeLights: [],
      sceneDepth: { texture: null, resolution: new THREE.Vector2(1, 1) },
      photoMode: false, replay: false,
      realTime: 0,
      width: window.innerWidth, height: window.innerHeight,
    };
    this.quality = new QualityManager(this.ctx.quality, () => this.ctx.settings.quality);

    this.sim = new Simulation(settings, this.ctx.events);
    this.env = new Environment(this.ctx);
    this.vehicles = new VehicleVisuals(this.ctx);
    this.vfx = new VFX(this.ctx);
    this.views = new ViewportManager(this.ctx, root);
    this.audio = new AudioEngine(this.ctx);

    const app = this;
    this.actions = {
      liftoffNow: () => app.sim.liftoffNow(),
      toggleHold: () => app.sim.toggleHold(),
      stageSeparation: () => app.sim.stageSeparation(),
      fairingSeparation: () => app.sim.fairingSeparation(),
      setWarp: (w) => app.sim.setWarp(w),
      togglePause: () => app.sim.setPaused(!app.sim.paused),
      setSetting: (key, value) => {
        app.ctx.settings[key] = value;
        app.sim.applySettings(app.ctx.settings);
        if (key === 'muted') app.audio.setMuted(value as boolean);
        app.ctx.events.emit({ type: 'SETTINGS_CHANGED', t: app.sim.getSnapshot().t, data: { key, value } });
      },
      setManualInput: (i) => app.sim.setManualInput(i),
      startReplay: () => {
        const h = app.sim.history;
        const td = app.sim.getSnapshot().timeline.find((m) => m.type === 'TOUCHDOWN' && m.done);
        const center = td ? td.t : h.end - 3;
        const from = Math.max(h.start, center - 12), to = Math.min(h.end, center + 5);
        if (to - from < 1) return;
        app.replayCtl.start(from, to);
        app.ctx.replay = true;
      },
      stopReplay: () => { app.replayCtl.active = false; app.ctx.replay = false; },
      togglePhotoMode: () => {
        app.ctx.photoMode = !app.ctx.photoMode;
        app.sim.setPaused(app.ctx.photoMode);
      },
      unlockAudio: () => { app.audio.unlock(); app.actions.setSetting('muted', false); },
      restart: () => location.reload(),
      getSummary: () => app.sim.getSummary(),
      cameraCommand: (cmd) => app.views.command(cmd),
      capturePhoto: () => new Promise((resolve) => {
        app.frame(0);
        app.ctx.renderer.domElement.toBlob((b) => resolve(b), 'image/png');
      }),
    };
    this.hud = new HUD(this.ctx, this.actions, root);

    window.addEventListener('resize', () => this.resize());
    this.resize();
    (window as unknown as { __app: App }).__app = this;
  }

  async start(): Promise<void> {
    await Promise.all([this.env.load(), this.vehicles.load(), this.vfx.load(), this.audio.load()]);
    this.views.applyUrlParams(this.params);
    const seek = this.params.get('seek');
    if (seek !== null) this.sim.seek(Number(seek));
    const warp = this.params.get('warp');
    if (warp) this.sim.setWarp(Number(warp));
    if (this.params.get('pause') === '1') this.sim.setPaused(true);
    this.last = performance.now();
    renderLoop(this);
  }

  private resize(): void {
    this.ctx.width = window.innerWidth;
    this.ctx.height = window.innerHeight;
    this.ctx.renderer.setSize(this.ctx.width, this.ctx.height);
  }

  /** One rendered frame. Exposed for deterministic stepping from tests: __app.frame(1/60). */
  frame(dtReal: number): void {
    const ctx = this.ctx;
    ctx.realTime += dtReal;
    this.quality.update(dtReal);

    let snap: SimSnapshot;
    if (this.replayCtl.active) {
      const rc = this.replayCtl;
      rc.t += dtReal * rc.speed;
      if (rc.t >= rc.end) this.actions.stopReplay();
      snap = this.sim.history.sample(Math.min(rc.t, rc.end)) ?? this.sim.getSnapshot();
    } else {
      this.sim.advance(dtReal);
      snap = this.sim.getSnapshot();
    }
    this.lastSnap = snap;

    this.env.update(snap, dtReal);
    this.vehicles.update(snap, dtReal);
    this.vfx.update(snap, dtReal);
    this.views.update(snap, dtReal);
    this.audio.update(snap, this.views.primaryView(), dtReal);
    this.hud.update(snap, this.views.views, dtReal);

    const r = ctx.renderer;
    r.setRenderTarget(null);
    r.setScissorTest(false);
    r.setClearColor(0x000000, 1);
    r.clear(true, true, true);

    const alive = new Set<string>();
    for (const view of this.views.views) {
      alive.add(view.id);
      if (view.alpha <= 0.001 || view.rect.w < 2 || view.rect.h < 2) continue;
      this.renderView(view, snap);
    }
    for (const [id, p] of this.posts) if (!alive.has(id)) { p.dispose(); this.posts.delete(id); }
    this.frameCount++;
  }

  private renderView(view: ViewInfo, snap: SimSnapshot): void {
    const ctx = this.ctx;
    ctx.renderOrigin.copy(view.camWorldPos);
    ctx.worldRoot.position.copy(view.camWorldPos).negate();
    view.camera.position.set(0, 0, 0);
    ctx.scene.updateMatrixWorld();
    this.env.beforeViewRender(view, snap);
    this.vehicles.beforeViewRender(view, snap);
    this.vfx.beforeViewRender(view, snap);
    ctx.scene.updateMatrixWorld();
    let post = this.posts.get(view.id);
    if (!post) this.posts.set(view.id, (post = new PostPipeline(ctx)));
    post.render(view);
  }

  tick(now: number): void {
    const dt = Math.min(0.1, Math.max(0, (now - this.last) / 1000));
    this.last = now;
    this.frame(dt);
  }
}

function renderLoop(app: App): void {
  const loop = (now: number) => {
    app.tick(now);
    requestAnimationFrame(loop);
  };
  requestAnimationFrame(loop);
}
